android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# Fix for Windows Illegal char <:> in build path
android.injected.build.model.only.versioned=3
